version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-checkout:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
  unit-test:
    executor:
      name: node/default
    steps:
      - run:
          command: npm run test       
  e2e-test:
    executor:
      name: node/default
    steps:
      - run:
          command: npm run test:e2e        
workflows:
  build-and-test:
    jobs:
      - build-and-checkout
      - unit-test
      - e2e-test
