version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
<<<<<<< HEAD
=======
      - run:
          command: npm run test:e2e
      - store_test_results:
          path: test-results
      
>>>>>>> 82d97f2... Updated config.yml
workflows:
  build-and-test:
    jobs:
      - build-and-test