version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - run:
          command: npm run test:e2e
      - store_test_results:
          path: ~/project/test-results      
workflows:
  build-and-test:
    jobs:
      - build-and-test